# image: tapis/flaskbase:fastapi
# Base image for building Tapis API services in Python/flask

## There's no ci for this as it's not used. Pods Service manually pip installs tapipy/tapisservice.

FROM python:3.10

RUN useradd tapis -u 4872
ADD requirements-fastapi.txt /home/tapis/tapisservice-requirements.txt

# TODO -- eventually remove this
RUN apt-get update && apt-get install -y vim

# Install requirements and tapipy/tapisservice(inside of requirements.txt) packages.
RUN pip install -U --no-cache-dir pip && \
    pip install --no-cache-dir -r /home/tapis/tapisservice-requirements.txt

WORKDIR /home/tapis

CMD ["echo", "This is a base image only"]
